name: Push to FTP-Server
on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".github"
  workflow_dispatch:
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**